.TH gts-config 1 "June 2, 2008" "" "GNU Triangulated Surface utils"

.SH NAME
gts-config \- defines values for programs using gts.

.SH SYNOPSIS
.B gts-config
.RI [\| OPTIONS \|]\ [\| LIBRARIES \|]
.SH DESCRIPTION
This manual page documents briefly the
.B gts-config
command.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.BI \-\-prefix\fR[\|= DIR \fR\|]
.TP
.BI \-\-exec-prefix\fR[\|= DIR \fR\|]
.TP
.B \-\-version
.TP
.B \-\-libs
.TP
.B \-\-cflags
.TP
.B \-\-check

.SH LIBRARIES
.TP
.B gts
.TP
.B gmodule
.TP
.B gthread

.SH AUTHOR
gts-config was written by Stephane Popinet <popinet@users.sourceforge.net>.
.PP
This manual page was written by Ruben Molina <rmolina@udea.edu.co>,
for the Debian project (but may be used by others).
