.TH gtstemplate 1 "June 2, 2008" "" "GNU Triangulated Surface utils"

.SH NAME
gtstemplate \- generates of a template used to create new object classes.

.SH SYNOPSIS
.B gtstemplate
.RI [\| OPTIONS \|]\ [\| LIBRARIES \|]

.SH DESCRIPTION
This manual page documents briefly the
.B gtstemplate
command.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-\-no-extra-data
.TP
.B \-\-no-extra-method
.TP
.BI \-\-overload= METHOD

.SH AUTHOR
gtstemplate was written by Stephane Popinet <popinet@users.sourceforge.net>.
.PP
This manual page was written by Ruben Molina <rmolina@udea.edu.co>,
for the Debian project (but may be used by others).
