.TH stl2gts 1 "June 2, 2008" "" "GNU Triangulated Surface utils"

.SH NAME
stl2gts \- convert an STL file to GTS format.

.SH SYNOPSIS
.B stl2gts
.RI [\| OPTIONS \|]\ <\  input.stl\  >\  output.gts

.SH DESCRIPTION
This manual page documents briefly the
.B stl2gts
command.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.BR \-r ,\  \-\-revert
Revert face normals.
.TP
.BR \-n ,\  \-\-nomerge
Do not merge vertices.
.TP
.BR \-v ,\  \-\-verbose
Display surface statistics.
.TP
.BR \-h ,\  \-\-help
Display the help and exit.

.SH AUTHOR
stl2gts was written by Stephane Popinet <popinet@users.sourceforge.net>.
.PP
This manual page was written by Ruben Molina <rmolina@udea.edu.co>,
for the Debian project (but may be used by others).
